### PR TITLE
Add support for React 17

### PR DESCRIPTION
**Pull request by thexpand**

### CODE REVIEW

**Comment by jamesplease** [comment]
Thanks! Will cut a release in a bit (today)

**Comment by thexpand** [comment]
Thanks! Will you add the corresponding PR to the changelog? I wasn't sure if I had to do it.

**Comment by jamesplease** [comment]
Yup, I'll take care of the changelog. Thanks!

**Comment by jamesplease** [comment]
Published as 5.0.2. Let me know if that works for ya ✌️

**Comment by thexpand** [comment]
Yup, all working good! Thank you for the quick response @jamesplease

**Comment by jamesplease** [comment]
Awesome! Thank _you_ for opening the PR!

**Pull request merged**
